---
- name: "awxrpm | install awx server"
  hosts: localhost
  roles:
    - role: awxvenv
      awx_image_version: "19.4.0"
      awx_user: "awx"
      awx_db_password: "dsfsdfds"
      awxpassword: "awx2know"
      postgreshost: "awxserver"
      postgresdata: "/var/lib/pgsql/data"
      nginx_disable_https: True
      nginx_http_port: 80
      nginx_disable_hsts: True
      nodejsversion: v14.x
      secret_key: werwerwer13dfdssdfsdfsdfsd32fds
      CLUSTER_HOST_ID: 'localhost'
      awx_install_pg_init_name: 'miracle'
      awx_install_redis_init_name: 'miracle'



      
