Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"

   config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name = "images"
    libvirt.driver = "qemu" # or kvm
   end
  
  
   #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
